package org.jfree.chart.renderer;
/** 
 * An exception that is generated by the                                                                                                                                                                {@link Outlier},                                                                                                                                                                {@link OutlierList}and                                                                                                                                                                {@link OutlierListCollection} classes.
 */
public class NotOutlierException extends Exception {
  /** 
 * Creates a new exception.
 * @param message  the exception message.
 */
  public NotOutlierException(  String message){
    super(message);
  }
}
